with open('src/App.jsx', 'r') as f:
    content = f.read()

changes = 0

lang_anchors = [
    ("Français",
     "    kpiTotalRevenue: 'Revenu total', chartNationalities: 'Nationalités des clients', chartTopResorts: 'Stations les plus fréquentées'\n  },",
     "    kpiTotalRevenue: 'Revenu total', chartNationalities: 'Nationalités des clients', chartTopResorts: 'Stations les plus fréquentées',\n    settingsSubtitle: 'Personnalisez votre compte et vos tarifs', sectionSubscription: 'Abonnement',\n    subscriptionDesc: 'Toutes les fonctionnalités incluses. Résiliable à tout moment.', loadingWait: 'Un instant...',\n    btnSubscribe: \"S'abonner\", activeSubscription: 'Abonnement actif', sectionCoordonnees: 'Coordonnées',\n    labelNomAffiche: 'Nom affiché', labelSiret: 'Numéro SIRET', labelAdressePostale: 'Adresse postale',\n    sectionBanque: 'Coordonnées bancaires (pour vos factures)', labelNomBanque: 'Nom de la banque',\n    sectionRegional: 'Préférences régionales', labelDevise: 'Devise', labelLangueInterface: \"Langue de l'interface\",\n    labelFuseau: 'Fuseau horaire', sectionSaisons: 'Périodes de saison', btnVacancesAuto: 'Vacances scolaires (auto)',\n    btnPeriodeManuelle: 'Période manuelle', labelZoneAcademique: 'Zone académique de référence',\n    optToutesZones: 'Toutes les zones (recommandé pour une clientèle nationale)',\n    seasonExplainAuto: \"La haute saison correspond automatiquement aux vacances de Noël, d'Hiver et de Printemps (dates officielles Éducation nationale 2025-2026 et 2026-2027). Toutes les zones prend la période la plus large, utile si vos clients viennent de toute la France.\",\n    seasonExplainManual: 'Toute date hors de cette période est considérée en basse saison.',\n    labelDebutHauteSaison: 'Début haute saison (MM-JJ)', labelFinHauteSaison: 'Fin haute saison (MM-JJ)',\n    sectionTarifsHoraires: 'Tarifs horaires', sectionTarifsForfait: 'Tarifs forfaitaires',\n    sectionHorairesDemi: 'Horaires des demi-journées', labelDebut: 'début', labelFin: 'fin',\n    sectionJoursRepos: 'Jours de repos', sectionApparence: 'Apparence', btnClair: 'Clair', btnSombre: 'Sombre',\n    sectionNotifications: 'Notifications', notifEmailLabel: 'Recevoir les confirmations par e-mail',\n    notifSmsLabel: 'Recevoir les rappels par SMS', settingsSaved: 'Paramètres enregistrés ✓'\n  },"),
    ("Anglais",
     "    kpiTotalRevenue: 'Total revenue', chartNationalities: 'Client nationalities', chartTopResorts: 'Most visited resorts'\n  },",
     "    kpiTotalRevenue: 'Total revenue', chartNationalities: 'Client nationalities', chartTopResorts: 'Most visited resorts',\n    settingsSubtitle: 'Customize your account and rates', sectionSubscription: 'Subscription',\n    subscriptionDesc: 'All features included. Cancel anytime.', loadingWait: 'One moment...',\n    btnSubscribe: 'Subscribe', activeSubscription: 'Active subscription', sectionCoordonnees: 'Contact details',\n    labelNomAffiche: 'Display name', labelSiret: 'SIRET number', labelAdressePostale: 'Postal address',\n    sectionBanque: 'Bank details (for your invoices)', labelNomBanque: 'Bank name',\n    sectionRegional: 'Regional preferences', labelDevise: 'Currency', labelLangueInterface: 'Interface language',\n    labelFuseau: 'Time zone', sectionSaisons: 'Season periods', btnVacancesAuto: 'School holidays (auto)',\n    btnPeriodeManuelle: 'Manual period', labelZoneAcademique: 'Reference academic zone',\n    optToutesZones: 'All zones (recommended for a national clientele)',\n    seasonExplainAuto: 'High season automatically follows the Christmas, Winter and Spring school holidays (official French National Education dates 2025-2026 and 2026-2027). \"All zones\" takes the widest period, useful if your clients come from all over France.',\n    seasonExplainManual: 'Any date outside this period is considered low season.',\n    labelDebutHauteSaison: 'High season start (MM-DD)', labelFinHauteSaison: 'High season end (MM-DD)',\n    sectionTarifsHoraires: 'Hourly rates', sectionTarifsForfait: 'Package rates',\n    sectionHorairesDemi: 'Half-day schedules', labelDebut: 'start', labelFin: 'end',\n    sectionJoursRepos: 'Days off', sectionApparence: 'Appearance', btnClair: 'Light', btnSombre: 'Dark',\n    sectionNotifications: 'Notifications', notifEmailLabel: 'Receive confirmations by email',\n    notifSmsLabel: 'Receive reminders by SMS', settingsSaved: 'Settings saved ✓'\n  },"),
    ("Espagnol",
     "    kpiTotalRevenue: 'Ingreso total', chartNationalities: 'Nacionalidades de los clientes', chartTopResorts: 'Estaciones más frecuentadas'\n  },",
     "    kpiTotalRevenue: 'Ingreso total', chartNationalities: 'Nacionalidades de los clientes', chartTopResorts: 'Estaciones más frecuentadas',\n    settingsSubtitle: 'Personaliza tu cuenta y tarifas', sectionSubscription: 'Suscripción',\n    subscriptionDesc: 'Todas las funciones incluidas. Cancela cuando quieras.', loadingWait: 'Un momento...',\n    btnSubscribe: 'Suscribirse', activeSubscription: 'Suscripción activa', sectionCoordonnees: 'Datos de contacto',\n    labelNomAffiche: 'Nombre mostrado', labelSiret: 'Número SIRET', labelAdressePostale: 'Dirección postal',\n    sectionBanque: 'Datos bancarios (para tus facturas)', labelNomBanque: 'Nombre del banco',\n    sectionRegional: 'Preferencias regionales', labelDevise: 'Moneda', labelLangueInterface: 'Idioma de la interfaz',\n    labelFuseau: 'Zona horaria', sectionSaisons: 'Períodos de temporada', btnVacancesAuto: 'Vacaciones escolares (auto)',\n    btnPeriodeManuelle: 'Período manual', labelZoneAcademique: 'Zona académica de referencia',\n    optToutesZones: 'Todas las zonas (recomendado para clientela nacional)',\n    seasonExplainAuto: 'La temporada alta sigue automáticamente las vacaciones escolares de Navidad, Invierno y Primavera (fechas oficiales de Educación Nacional francesa 2025-2026 y 2026-2027). \"Todas las zonas\" toma el período más amplio, útil si tus clientes vienen de toda Francia.',\n    seasonExplainManual: 'Cualquier fecha fuera de este período se considera temporada baja.',\n    labelDebutHauteSaison: 'Inicio temporada alta (MM-DD)', labelFinHauteSaison: 'Fin temporada alta (MM-DD)',\n    sectionTarifsHoraires: 'Tarifas por hora', sectionTarifsForfait: 'Tarifas de paquete',\n    sectionHorairesDemi: 'Horarios de media jornada', labelDebut: 'inicio', labelFin: 'fin',\n    sectionJoursRepos: 'Días de descanso', sectionApparence: 'Apariencia', btnClair: 'Claro', btnSombre: 'Oscuro',\n    sectionNotifications: 'Notificaciones', notifEmailLabel: 'Recibir confirmaciones por correo electrónico',\n    notifSmsLabel: 'Recibir recordatorios por SMS', settingsSaved: 'Ajustes guardados ✓'\n  },"),
    ("Italien",
     "    kpiTotalRevenue: 'Ricavo totale', chartNationalities: 'Nazionalità dei clienti', chartTopResorts: 'Stazioni più frequentate'\n  },",
     "    kpiTotalRevenue: 'Ricavo totale', chartNationalities: 'Nazionalità dei clienti', chartTopResorts: 'Stazioni più frequentate',\n    settingsSubtitle: 'Personalizza il tuo account e le tariffe', sectionSubscription: 'Abbonamento',\n    subscriptionDesc: 'Tutte le funzionalità incluse. Annullabile in qualsiasi momento.', loadingWait: 'Un momento...',\n    btnSubscribe: 'Abbonati', activeSubscription: 'Abbonamento attivo', sectionCoordonnees: 'Dati di contatto',\n    labelNomAffiche: 'Nome visualizzato', labelSiret: 'Numero SIRET', labelAdressePostale: 'Indirizzo postale',\n    sectionBanque: 'Dati bancari (per le tue fatture)', labelNomBanque: 'Nome della banca',\n    sectionRegional: 'Preferenze regionali', labelDevise: 'Valuta', labelLangueInterface: \"Lingua dell'interfaccia\",\n    labelFuseau: 'Fuso orario', sectionSaisons: 'Periodi stagionali', btnVacancesAuto: 'Vacanze scolastiche (auto)',\n    btnPeriodeManuelle: 'Periodo manuale', labelZoneAcademique: 'Zona accademica di riferimento',\n    optToutesZones: 'Tutte le zone (consigliato per una clientela nazionale)',\n    seasonExplainAuto: \"L'alta stagione segue automaticamente le vacanze scolastiche di Natale, Inverno e Primavera (date ufficiali dell'Istruzione Nazionale francese 2025-2026 e 2026-2027). \\\"Tutte le zone\\\" prende il periodo più ampio, utile se i tuoi clienti vengono da tutta la Francia.\",\n    seasonExplainManual: 'Qualsiasi data al di fuori di questo periodo è considerata bassa stagione.',\n    labelDebutHauteSaison: 'Inizio alta stagione (MM-GG)', labelFinHauteSaison: 'Fine alta stagione (MM-GG)',\n    sectionTarifsHoraires: 'Tariffe orarie', sectionTarifsForfait: 'Tariffe forfettarie',\n    sectionHorairesDemi: 'Orari mezza giornata', labelDebut: 'inizio', labelFin: 'fine',\n    sectionJoursRepos: 'Giorni di riposo', sectionApparence: 'Aspetto', btnClair: 'Chiaro', btnSombre: 'Scuro',\n    sectionNotifications: 'Notifiche', notifEmailLabel: 'Ricevi conferme via e-mail',\n    notifSmsLabel: 'Ricevi promemoria via SMS', settingsSaved: 'Impostazioni salvate ✓'\n  },"),
    ("Portugais",
     "    kpiTotalRevenue: 'Receita total', chartNationalities: 'Nacionalidades dos clientes', chartTopResorts: 'Estações mais frequentadas'\n  }\n};",
     "    kpiTotalRevenue: 'Receita total', chartNationalities: 'Nacionalidades dos clientes', chartTopResorts: 'Estações mais frequentadas',\n    settingsSubtitle: 'Personalize sua conta e tarifas', sectionSubscription: 'Assinatura',\n    subscriptionDesc: 'Todos os recursos incluídos. Cancele quando quiser.', loadingWait: 'Um momento...',\n    btnSubscribe: 'Assinar', activeSubscription: 'Assinatura ativa', sectionCoordonnees: 'Dados de contato',\n    labelNomAffiche: 'Nome exibido', labelSiret: 'Número SIRET', labelAdressePostale: 'Endereço postal',\n    sectionBanque: 'Dados bancários (para suas faturas)', labelNomBanque: 'Nome do banco',\n    sectionRegional: 'Preferências regionais', labelDevise: 'Moeda', labelLangueInterface: 'Idioma da interface',\n    labelFuseau: 'Fuso horário', sectionSaisons: 'Períodos de temporada', btnVacancesAuto: 'Férias escolares (auto)',\n    btnPeriodeManuelle: 'Período manual', labelZoneAcademique: 'Zona acadêmica de referência',\n    optToutesZones: 'Todas as zonas (recomendado para clientela nacional)',\n    seasonExplainAuto: 'A época alta segue automaticamente as férias escolares de Natal, Inverno e Primavera (datas oficiais da Educação Nacional francesa 2025-2026 e 2026-2027). \"Todas as zonas\" considera o período mais amplo, útil se seus clientes vêm de toda a França.',\n    seasonExplainManual: 'Qualquer data fora deste período é considerada época baixa.',\n    labelDebutHauteSaison: 'Início da época alta (MM-DD)', labelFinHauteSaison: 'Fim da época alta (MM-DD)',\n    sectionTarifsHoraires: 'Tarifas por hora', sectionTarifsForfait: 'Tarifas de pacote',\n    sectionHorairesDemi: 'Horários de meio período', labelDebut: 'início', labelFin: 'fim',\n    sectionJoursRepos: 'Dias de folga', sectionApparence: 'Aparência', btnClair: 'Claro', btnSombre: 'Escuro',\n    sectionNotifications: 'Notificações', notifEmailLabel: 'Receber confirmações por e-mail',\n    notifSmsLabel: 'Receber lembretes por SMS', settingsSaved: 'Configurações salvas ✓'\n  }\n};"),
]

for name, old, new in lang_anchors:
    if old in content:
        content = content.replace(old, new, 1)
        changes += 1
        print(f"OK - Cles parametres ajoutees pour {name}")
    else:
        print(f"ERREUR - Bloc {name} non trouve")

with open('src/App.jsx', 'w') as f:
    f.write(content)

print(f"\n{changes} modifications appliquees (Etape 9a/N - cles Parametres).")
